export const SAMPLE_VISITORS = [
  {
    name: "Sample Visitor (Balanced)",
    Administrative: 2,
    Administrative_Duration: 60,
    Informational: 1,
    Informational_Duration: 30,
    ProductRelated: 12,
    ProductRelated_Duration: 450,
    BounceRates: 2,
    ExitRates: 5,
    PageValues: 15,
    SpecialDay: 0,
    OperatingSystems: 2,
    Browser: 2,
    Region: 1,
    TrafficType: 2,
    Weekend: true,
    Month: "Nov",
    VisitorType: "Returning Visitor"
  },
  {
    name: "High-Intent Hot Buyer",
    Administrative: 4,
    Administrative_Duration: 120,
    Informational: 2,
    Informational_Duration: 90,
    ProductRelated: 38,
    ProductRelated_Duration: 1450,
    BounceRates: 0.2,
    ExitRates: 1.5,
    PageValues: 48.6,
    SpecialDay: 0,
    OperatingSystems: 2,
    Browser: 2,
    Region: 3,
    TrafficType: 3,
    Weekend: true,
    Month: "Dec",
    VisitorType: "Returning Visitor"
  },
  {
    name: "Low-Engagement Bounce Visitor",
    Administrative: 0,
    Administrative_Duration: 0,
    Informational: 0,
    Informational_Duration: 0,
    ProductRelated: 2,
    ProductRelated_Duration: 8,
    BounceRates: 20,
    ExitRates: 50,
    PageValues: 0,
    SpecialDay: 0.8,
    OperatingSystems: 1,
    Browser: 1,
    Region: 1,
    TrafficType: 4,
    Weekend: false,
    Month: "May",
    VisitorType: "New Visitor"
  }
];
